### ISSUE TITLE
The tests for DelayedButton don't test for the delay prop.

### ISSUE THREAD

**Issue by pickledyamsman** [learn-co-students/react-events-in-detail-lab-learn-experts-testing-batch#4]
The instructions say that DelayedButton.js should have a setTimeout() block that uses the delay prop. But the following code will pass all of the tests for the file. Maybe another test just for that part?

```
import React from 'react';

class DelayedButton extends React.Component {
  constructor() {
    super();
    this.delayClicker = this.delayClicker.bind(this);
  }

  delayClicker(event){
    event.persist()
    this.props.onDelayedClick(event)
  }

  render(){
    return (
      <button onClick={this.delayClicker}>Delay Button</button>
    )
  }
}

module.exports = DelayedButton;
```

**Comment by pickledyamsman** [comment]
@aturkewi

**Comment by aturkewi** [comment]
@pickledyamsman Thanks for making an issue on this :)
Can you please raise the issue in the appropriate place though? That would be on `learn-co-curriculum` -> https://github.com/flatiron-labs/learn-support/blob/master/how-to-raise-an-issue.md#how-to-raise-an-issue
